### ISSUE TITLE
Apresentar o exemplo de acesso a Ontologias utilizando a biblioteca JENA

### ISSUE THREAD

**Issue by evaldo** [evaldo/semanticannotation#2]

**Comment by evaldo** [comment]
[Semantic Annotation and Retrieval.pdf](https://github.com/evaldo/semanticannotation/files/881978/Semantic.Annotation.and.Retrieval.pdf)

**Comment by evaldo** [comment]
Links to access JENA library using Java language:
- http://www.iandickinson.me.uk/articles/jena-eclipse-helloworld/
- https://github.com/castagna/jena-examples/tree/master/src/main/java/org/apache/jena/examples- 
- https://jena.apache.org/tutorials/using_jena_with_eclipse_pt.html
https://jena.apache.org/tutorials/rdf_api.html

**Comment by FilipeQuina** [comment]
http://www.goncalves.pro.br/artigos/goncalvesFrozzaApresentacaoJena.pdf

**Comment by evaldo** [comment]
Tutorial regarding JENA library which presents resources using applied to JAVA language:
[jena.pdf](https://github.com/evaldo/semanticannotation/files/884041/jena.pdf)

**Comment by evaldo** [comment]
Olá Felipe!
É importante que você estruture o projeto JAVA criado para testar a JENA, e que também poderá ser utilizado para a construção protótipo. Faça os comentários sobre os métodos de acesso à ontologia URBANUS.owl.
